version: "3.6"

services:
  proxy-server:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/auth/auth.sock:/etc/nginx/auth.sock
    ports:
      - "8080:8080"
    depends_on:
      - flask

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main_rest_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin