version: "3.6"

services:
  proxy-server:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/auth/auth.sock:/etc/nginx/auth.sock
    ports:
      - "8080:8080"
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile.Python
    working_dir: /app
    expose:
      - '3031'
    volumes:
      - ./app/auth:/app
    command: /bin/sh -c "pip install -r requirements.txt && uwsgi --ini auth.ini"

  java-service:
    image: openjdk:11-stretch
    working_dir: /app
    ports:
      - "8090:8090"
    volumes:
      - ./app/main-rest-service/target/main-rest-service-0.1.0.jar:/app/main-rest-service-0.1.0.jar
    command: java -jar main-rest-service-0.1.0.jar