version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main_rest_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  frontend:
    image: node:10
    working_dir: /app
    volumes:
      - "./app/frontend:/app"
    command: /bin/sh -c "npm install && npm install -g @angular/cli && ng serve --host 0.0.0.0 --port 4201 --disable-host-check"
    ports:
      - "4201:4201"

  django:
    build:
      context: .
      dockerfile: Dockerfile.Python3
    working_dir: /app
    volumes:
      - "./app/main_rest_service:/app"
    command: /app/start.sh
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    environment:
      - 'SECRET=$sc7z*$mub!&n6ppy6x&c$irlk84=#5i-7jqm)xyj@=qd=nnf1'

  device:
    image: pypy:3.6
    working_dir: /app
    volumes:
      - "./app/device_microservice:/app"
    command: /bin/sh -c "pip install -r requirements.txt && alembic upgrade head && gunicorn --reload -b 0.0.0.0:8081 main:app -w 4 -k uvicorn.workers.UvicornH11Worker"
#    command: /bin/sh -c "pip install -r requirements.txt && alembic upgrade head && uvicorn main:app"
    environment:
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'DATABASE_URL=sqlite:///./test.db'
      - 'SECRET=$sc7z*$mub!&n6ppy6x&c$irlk84=#5i-7jqm)xyj@=qd=nnf1'
    depends_on:
      - redis
    ports:
      - "8081:8081"

  sous_vide:
    image: clojure:latest
    working_dir: /app
    volumes:
      - "./app/sous_vide_microservice:/app"
    depends_on:
      - redis
      - mosquitto
    ports:
      - "7889:7889"
    command: /bin/bash -c "lein run"
#    command: lein repl :headless :host 0.0.0.0 :port 7888

  redis:
    image: redis:latest
    expose:
      - 6379

  mosquitto:
    image: eclipse-mosquitto:latest
    expose:
      - 1883
